name: chirperproject
recipe: laravel
config:
  webroot: public
  database: mysql
  php: 8.1
  config:
    php: config/php.ini
services:
  node:
    type: node:14
    build:
      - npm install
tooling:
  npm:
    service: node
  node:
    service: node
